"use strict";
/* =====================================================================
   GESCHICHTE: ORTSCHRONIK, ERKUNDUNGEN UND WEGBUCH
   Hier stehen die längeren Texte des Spiels. Du kannst sie frei
   umschreiben. Achte nur darauf, dass Anführungszeichen im Text als
   „…“ oder »…« geschrieben werden, nicht als gerade Zeichen ".
   ===================================================================== */

// Ortschronik: Ortsgeschichte aus Gemeindechronik, Wappentext und örtlichen Themenwegen.
// Spielfiguren und Quests erzählen ihre eigene Geschichte; die Chronik bleibt quellengebunden.
const CHRONICLE=[
  {id:"fulinpah980",phase:1,place:"rathaus",date:"980",title:"Fulinpah und der langsame Bach",
    paragraphs:["Im Jahr 980 taucht Feilnbach erstmals urkundlich als „Fulinpah“ auf. Der Name wird als „fauler Bach“ gedeutet: gemeint ist ein träge oder langsam fließendes Gewässer. Namen bewahren damit einen Blick auf die Landschaft, der lange vor den heutigen Straßenschildern entstand.","Der Jenbach setzt einen hörbaren Gegenpol. Die Gemeindechronik erklärt seinen Namen als „jähen Bach“ und beschreibt ihn als wild und ungestüm. Von den Vorbergen des Wendelsteinmassivs reichen die Gemeindeflächen bis in die Filz- und Moorgebiete des Rosenheimer Beckens. Wenn du den Namen Fulinpach in der Kiste liest, denke an diese beiden unterschiedlichen Wasserläufe."],
    question:"Welche beiden Bachbilder gehören in deine Notiz?",answers:["Fulinpah: langsam; Jenbach: jäh.","Fulinpah: jäh; Jenbach: langsam."],correct:0,
    source:"Gemeinde Bad Feilnbach · Gemeindechronik",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/gemeindechronik/"},
  {id:"wappen1391",phase:1,place:"kirche",date:"1391 / 1965",title:"Kirche und Wellenbalken im Wappen",
    paragraphs:["Das Gemeindewappen zeigt über einem silbernen Wellenbalken eine silberne Kirche. Die Kirche nimmt das Wappen der Herren von Diepertskirchen auf, die mit der mittelalterlichen Geschichte des Ortes verbunden waren. Ihre Wappenform ist auf einem Grabstein von 1391 überliefert.","Der Wellenbalken spricht den Ortsnamen aus: Er verweist auf Feilnbach, das frühere Fulinpah und den langsamen Bach. Erst 1965 erhielt die Gemeinde die Zustimmung, dieses Wappen zu führen. So stehen ein mittelalterliches Zeichen und der Wassername gemeinsam auf einem jüngeren amtlichen Bild."],
    question:"Was verbindet die beiden Teile des Wappens?",answers:["Ein alter Bahnfahrplan und der Apfelmarkt.","Die Kirche der Diepertskirchener und der Bach im Ortsnamen."],correct:1,
    source:"Gemeinde Bad Feilnbach · Wappenbeschreibung",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/buergermeisterbuero/"},
  {id:"bahn1897",phase:1,place:"bahnhof",date:"1897–1973",title:"Die elektrische Bahn nach Feilnbach",
    paragraphs:["Am 29. Mai 1897 wurde die Strecke zwischen Bad Aibling und dem damaligen Feilenbach feierlich eingeweiht. Sie gehörte zu den frühen elektrifizierten Eisenbahnen Bayerns. Mit ihr änderte sich, wie Waren und Gäste den Ort erreichten; die Gemeindechronik verbindet die Bahn mit wirtschaftlichem Aufschwung entlang der Strecke.","Im September 1973 endete der Betrieb aus wirtschaftlichen Gründen. Das ist dasselbe Jahr, in dem Feilnbach den Zusatz „Bad“ erhielt. Am ehemaligen Bahnhof begegnen sich daher zwei Bewegungen: ein Verkehrsweg verschwindet, während der Kurort seinen Namen erweitert. Teile der ehemaligen Trasse sind heute als Radweg erlebbar."],
    question:"Welche beiden Ereignisse gehören zum Jahr 1973?",answers:["Erste Erwähnung und Bau der Kapelle.","Ende der Lokalbahn und Erhebung zum Bad."],correct:1,
    source:"Gemeinde Bad Feilnbach · Gemeindechronik",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/gemeindechronik/"},
  {id:"moor1900",phase:1,place:"filze",date:"seit 1900",title:"Das Moor und der Kurort",
    paragraphs:["Die reichhaltigen Moorvorkommen wurden seit etwa 1900 zur Grundlage für den Ausbau der Kureinrichtungen. Das „schwarze Gold“ prägte die Entwicklung zur Kur- und Fremdenverkehrsgemeinde. 1973 wurde Feilnbach zum Bad erhoben. Wer heute auf einem Bohlenweg steht, sieht also auch einen Teil der Wirtschafts- und Gesundheitsgeschichte des Ortes.","In den Sterntaler Filzen erinnert ein Torfstadel an den Abbau. Dort werden historische Werkzeuge gezeigt; ein Schauhandtorfstich erklärt die Arbeit im Moor. Der Boden ist zugleich Lebensraum. Den Weg zu respektieren heißt, die Spuren früherer Nutzung zu verstehen und die heutige Landschaft zu schonen."],
    question:"Wodurch wuchsen die Kureinrichtungen seit etwa 1900?",answers:["Durch die Moorvorkommen.","Durch einen neuen Gipfelbahnhof."],correct:0,
    source:"Gemeindechronik und Moorerlebnis Sterntaler Filze",url:"https://www.bad-feilnbach.de/kur-und-tourismus/themenwege/moorerlebnis-sterntaler-filze/"},
  {id:"gemeinde1978",phase:2,place:"au",date:"1972 / 1978",title:"Aus mehreren Gemeinden wird Bad Feilnbach",
    paragraphs:["Die heutige Gemeinde entstand während der Gebietsreform in den Jahren 1972 und 1978. Die Gemeindechronik nennt als Teile Feilnbach, Wiechs, Au bei Bad Aibling, Dettendorf und Litzldorf. Auf der Karte liegen sie nicht wie Häuser an einer einzigen Straße: Jeder Ort hat einen eigenen Mittelpunkt und eine eigene Vergangenheit.","An der Taxakapelle in Au merkst du, wie viel Geschichte ein heutiger Gemeindename zusammenfasst. Die Bezeichnung „Bad Feilnbach“ steht für eine Verwaltungseinheit; die Namen Au, Wiechs oder Litzldorf bleiben dennoch wichtig, wenn Menschen Wege erklären, Feste feiern oder von früher erzählen. Eine Ortschronik besteht gerade aus diesen Stimmen nebeneinander."],
    question:"Welche Orte nennt die Gemeindechronik bei der Entstehung?",answers:["Feilnbach, Wiechs, Au, Dettendorf und Litzldorf.","Nur Feilnbach und Au."],correct:0,
    source:"Gemeinde Bad Feilnbach · Gemeindechronik",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/gemeindechronik/"},
  {id:"apfel1992",phase:2,place:"markt",date:"seit 1992",title:"Streuobst und Apfelmarkt",
    paragraphs:["Rund 25.000 Bäume im Streuobstanbau prägen nach Angaben der Gemeinde die Kulturlandschaft um Bad Feilnbach. Obstbau ist für landwirtschaftliche Betriebe ein zusätzlicher Erwerbszweig und zugleich ein sichtbarer Teil der Landschaft. Alte Sorten und unterschiedliche Ernten gehören zu den Gründen, warum hier Äpfel weit mehr sind als eine Spielwährung.","1992 wurde erstmals zum Bad Feilnbacher Apfelmarkt eingeladen. Aus der Idee zur Vermarktung heimischen Obstes wurde ein weithin bekannter Markt, der im Oktober stattfindet. Zwischen den Ständen gehen Sortennamen, Rezepte und Erfahrungen weiter. Im Wegbuch zählt deshalb nicht nur, wie viele Äpfel du gesammelt hast, sondern wem du ihre Geschichte erzählen kannst."],
    question:"Wofür stand der erste Apfelmarkt 1992?",answers:["Für die Einstellung der Bahn.","Für die Vermarktung heimischen Obstes."],correct:1,
    source:"Gemeindechronik und Gemeindezeitung 2023",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/gemeindechronik/"},
  {id:"maler",phase:2,place:"wiechs",date:"19. Jahrhundert",title:"Leibl und Sperl in Kutterling",
    paragraphs:["Die Gemeindechronik nennt Wilhelm Leibl und Johann Sperl als Maler, die mehrere Jahre in Kutterling wirkten. Auf dem Weg zwischen Wiechs, den Obstwiesen und den kleineren Orten wird verständlich, weshalb eine Landschaft auch durch Bilder weiterlebt: Menschen sehen denselben Hang, aber wählen verschiedene Einzelheiten aus.","Kutterling ist nicht Wiechs. Der Eintrag beginnt hier, weil dein Wegbuch die benachbarten Orte verbindet. Nimm dir Zeit für den Blick über die Wiesen und zeichne dir einen Ausschnitt ein: den Baum, den Bach oder die Straße. Ein Bild bewahrt, was ein Verzeichnis von Namen allein nicht halten kann."],
    question:"Welche beiden Maler nennt die Gemeindechronik für Kutterling?",answers:["Leibl und Sperl.","Dientzenhofer und Fuetterer."],correct:0,
    source:"Gemeinde Bad Feilnbach · Gemeindechronik",url:"https://www.bad-feilnbach.de/buerger-und-rathaus/gemeindechronik/"},
  {id:"sterntaler",phase:2,place:"filze",date:"nach der Eiszeit / 2021",title:"Vom Rosenheimer See zum Moor",
    paragraphs:["Die Sterntaler Filze gehören zu den Rosenheimer Stammbeckenmooren. Nach dem Rückzug des Inngletschers bestand der Rosenheimer See; durch seine Verlandung entstanden Moorlandschaften. Torf bewahrt Spuren dieser langen Veränderung. Ein Gang durch die Filze führt deshalb durch eine Landschaft, die über sehr viel längere Zeiträume gewachsen ist als der Ort auf der Karte.","Heute leben dort seltene Pflanzen und Vögel; die örtliche Information nennt auch Moorfrosch und Wiesenweihe. 2021 wurde das Gebiet als Feuchtgebiet von internationaler Bedeutung ausgezeichnet. Bohlenweg, Vogelbeobachtung und Torfstadel erzählen zusammen von Nutzung und Schutz. Der Frosch im Spiel wird plötzlich zu einem guten Grund, beim Gehen genauer hinzusehen."],
    question:"Wie entstanden die Moorlandschaften laut der Ortsinformation?",answers:["Durch die Stilllegung der Eisenbahn.","Durch die Verlandung des Rosenheimer Sees."],correct:1,
    source:"Gemeinde Bad Feilnbach · Sterntaler Filze",url:"https://www.bad-feilnbach.de/kur-und-tourismus/themenwege/moorerlebnis-sterntaler-filze/"}
];

// Kleine Begegnungen mit einer Entscheidung. Belohnung: apples, seeds oder bark.
const ENCOUNTERS=[
  {id:"filze",place:"filze",title:"Der Pfosten im Moor",intro:"Neben dem Bohlenweg steht ein schiefer Pfosten. Zwei Besucher wollen ihn als Wegweiser benutzen; der Moorfrosch verschwindet zwischen den Binsen. Die Zeichnung auf dem Holz zeigt den festen Rand des Wegs, aber nicht seinen Zustand heute.",
    choices:[{id:"mark",label:"Den sicheren Bohlenweg kenntlich machen",text:"Du markierst die tragfähigen Bohlen. Die Besucher bleiben auf dem Weg und lassen dir 10 Kerne für die Streuobstwiese da.",seeds:10},{id:"frog",label:"Den Frosch vom Steg aus beobachten",text:"Du bleibst auf dem Steg. Dort, wo der Frosch innehält, entdeckst du den alten Torfstich. Die spätere Suche im Moos braucht weniger Kerne."}]},
  {id:"bahnhof",place:"bahnhof",title:"Ein Fahrplan ohne Gleise",intro:"Auf der Rückseite der Fahrkarte ist eine handgezogene Linie. Ein alter Bahnreisender erkennt einen Weg, der auf heutigen Karten kaum zu sehen ist. Er fragt dich, ob die Linie einen neuen Zweck bekommen oder als Fundstück bewahrt werden soll.",
    choices:[{id:"route",label:"Die alte Linie als Wegskizze abzeichnen",text:"Du zeichnest die Linie ins Wegbuch. Ein Ortskundiger erkennt später den Umweg im Jenbachtal; seine Hilfe kostet dich weniger Äpfel."},{id:"archive",label:"Die Fahrkarte dem Ortsarchiv zeigen",text:"Der Reisende ergänzt eine Erinnerung an die letzte Fahrt. Zwischen den Papieren findest du zwei Rindenzeichen.",bark:2}]},
  {id:"osterbach",place:"osterbach",title:"Die Zeichnung der Spielrinnen",intro:"Ein Kind hat die trockenen Spielrinnen im Kies nachgezeichnet. Der Weg des Wassers endet nicht am Damm: Daneben sind eine Zuleitung und die Häuser der Helfer eingezeichnet. Welchem Hinweis gehst du nach?",
    choices:[{id:"survey",label:"Die Rinnen mit der Zeichnung vermessen",text:"Du vermisst die Rinnen und gibst der Fachstelle eine brauchbare Skizze. Für den kontrollierten Ablauf werden später weniger Kerne benötigt."},{id:"neighbors",label:"Die Helfer auf der Zeichnung aufsuchen",text:"Die Nachbarn kennen schon einen sicheren Weg zur Versorgung des Spielplatzes. Für die gemeinsame Lösung werden später weniger Äpfel benötigt."}]},
  {id:"wiechs",place:"wiechs",title:"Ein Baum ohne Schild",intro:"Neben dem namenlosen Baum liegen Falläpfel und ein trockenes Pfropfreis. Eine Nachbarin fragt, ob du den nächsten Austrieb vorbereiten oder die heutige Ernte teilen möchtest. Beides bewahrt etwas anderes.",
    choices:[{id:"graft",label:"Das Pfropfreis für die nächste Ernte sichern",text:"Du zeigst der Nachbarin, welches Holz zum Baum gehört. Für die nächsten jungen Bäume gibt sie dir 15 Kerne.",seeds:15},{id:"share",label:"Die Falläpfel gemeinsam sortieren und teilen",text:"Die Nachbarn erkennen die Sorte am Geschmack. Sie legen 60 Äpfel für deinen weiteren Weg zurück.",apples:60}]}
];

// Wegbuch-Spuren. Kapitel 1 vor der Treppe, Kapitel 2 danach.
const LORE_THREADS=[
  {id:"name",title:"Die erste Silbe",chapter:1,places:["rathaus","bahnhof"],
    intro:{rathaus:"Am Sockel der Apfelkiste sitzt eine Kerbe unter vielen Jahresringen.",bahnhof:"Neben der alten Bahntrasse liegt ein Grenzstein mit verwitterten Buchstaben."},
    story:{rathaus:"Du reibst Erde aus der Kerbe. Unter dem Schmutz steht FULINPAH. In einer Urkunde von 980 hieß Feilnbach so: der träge, der faule Bach. Warum hat jemand den Namen in eine Kiste geschnitten, die selbst Äpfel hervorbringt? Unter dem letzten Buchstaben führt eine feine Linie weiter wie ein Wasserlauf.",bahnhof:"Auf dem Stein treffen zwei Zeiten aufeinander. Ein Pfeil zeigt zur Bahn, die 1897 Bad Aibling und Feilnbach verband; darunter ist ein viel älteres Wort eingeritzt: FULINPAH. Die Schienen sind fort, der Name blieb. Die eingeritzte Linie endet dort, wo die Apfelwiesen beginnen."},
    choices:[{label:"Den Namen laut aussprechen",text:"Du sprichst Fulinpah. Im Holz der Kiste antwortet ein einzelner Tropfen, obwohl sie trocken ist."},{label:"Die Linie ins Wegbuch zeichnen",text:"Du zeichnest die geschwungene Linie ab. Sie ähnelt keinem Fahrplan, aber dem Verlauf eines langsamen Bachs."}]},
  {id:"moor",title:"Was das Moor bewahrt",chapter:1,places:["filze","kirche"],
    intro:{filze:"Am Bohlenweg ragt ein Stück dunkles Holz aus dem Torf.",kirche:"An der Kirchentür steckt ein altes Blatt zwischen zwei Brettern."},
    story:{filze:"Das Holz ist glatt, als hätte es lange im Wasser gelegen. Unter deinen Fingern treten Jahresringe hervor; nicht einer erzählt von Eile. Das Moor bewahrt Dinge, die auf dem trockenen Weg längst zerfallen wären. Ein Frosch setzt sich genau auf den letzten Ring und schaut zu dir, bis du aufhörst zu ziehen.",kirche:"Auf dem Blatt steht kein Gebet, sondern eine Wegbeschreibung: Wer das Filz quert, soll auf den Bohlen bleiben und die stillen Stellen nicht betreten. Zwischen den Zeilen hat jemand einen Apfelbaum gezeichnet. Seine Wurzeln reichen tiefer als die Kirchentür hoch ist."},
    choices:[{label:"Das Holz an seinem Platz lassen",text:"Du lässt das Holz liegen und merkst dir seine Ringe. Manches bleibt nur erhalten, wenn man es nicht mitnimmt."},{label:"Die Geschichte weitererzählen",text:"Du erzählst vom Holz und dem Bohlenweg. Das Moor gibt keine Antwort, aber jemand wird beim nächsten Gang auf den Weg achten."}]},
  {id:"water",title:"Zwei Bäche, ein Tal",chapter:1,places:["osterbach","jenbach"],
    intro:{osterbach:"In einer trockenen Spielrinne liegt ein Stein mit zwei eingeritzten Wellen.",jenbach:"An der Jenbachbrücke sind zwei Pegelstriche in das Geländer geschnitten."},
    story:{osterbach:"Kinder haben die Holzrinnen zu einem kleinen Flusssystem verbunden. Jetzt bleibt der erste Lauf trocken. Der Stein zeigt zwei Wellen: eine gerade und eine, die an einem Hindernis ausweicht. Wer Wasser zurückbringen will, muss verstehen, wo es hinfließt, ohne das Zuhause der Biber zu zerstören.",jenbach:"Der obere Strich stammt aus einer Nacht, über die niemand gern spricht. Unter dem zweiten hat jemand ein Haus und daneben einen Apfelbaum eingeritzt. Der Jenbach kann jäh werden; sein Name klingt schon wie eine Warnung. Beim nächsten Regen zählen zuerst die Menschen unterhalb der Brücke."},
    choices:[{label:"Den Wasserweg nachzeichnen",text:"Du zeichnest beide Wellen nach. Wasser lässt sich lenken, aber eine Geschichte darüber muss auch die Häuser am Ufer enthalten."},{label:"Nach den Menschen am Bach fragen",text:"Du fragst, wer am Bach wohnt. Aus einer Linie auf Holz werden Wege, Türen und Namen, die man warnen kann."}]},
  {id:"harvest",title:"Der Baum ohne Schild",chapter:2,places:["markt","wiechs"],
    intro:{markt:"Zwischen Sortenschildern liegt eine Karte ohne Namen.",wiechs:"Ein alter Baum trägt Äpfel, aber sein Schild ist leer."},
    story:{markt:"Seit 1992 kommen auf dem Feilnbacher Apfelmarkt Menschen wegen der alten Sorten zusammen. Die namenlose Karte passt zu keiner Kiste. Hinten steht nur: 'Was niemand teilt, kann niemand wiederfinden.' Eine Händlerin legt einen Apfel daneben und wartet ab, ob du zuerst den Preis oder den Namen fragst.",wiechs:"Der Baum steht etwas abseits der übrigen Reihen. Seine Äpfel sind nicht die größten, aber jeder Kern hat dieselbe dunkle Zeichnung. Niemand weiß mehr, wer ihn pflanzte. In der Chronik fehlt eine Seite; in deiner Hand liegt vielleicht ihr lebender Rand."},
    choices:[{label:"Einen Kern für später aufheben",text:"Du verwahrst einen Kern und lässt die übrigen am Baum. Der Name einer Sorte darf nicht am letzten Exemplar hängen."},{label:"Einen Apfel weiterreichen",text:"Du gibst den Apfel weiter. Bald vergleichen mehrere Menschen Geschmack und Kerne, statt nur ein Schild zu suchen."}]},
  {id:"promise",title:"Das Gelübde von Au",chapter:2,places:["au","kirche"],
    intro:{au:"Unter den Zweigen bei der Taxakapelle findest du eine eingerollte Notiz.",kirche:"Auf einer Kirchenbank liegt eine Notiz mit dem Wort TAXA."},
    story:{au:"Balthasar Fuetterer gab 1647 ein Gelübde ab, aus dem die Taxakapelle erwuchs. Der Name Taxa erinnert an 'Daxn', die Fichten- und Tannenzweige bei der Kapelle. Die Notiz erzählt von einer anderen Art Versprechen: Wer im Herbst erntet, lässt im Frühjahr etwas wachsen, das ihm selbst vielleicht nie gehören wird.",kirche:"Das Papier riecht nach Nadelholz. Ein Pilger hat von der Kapelle in Au und einem Gelübde aus dem Jahr 1647 geschrieben. Darunter steht, in anderer Hand: Ein Versprechen gilt auch, wenn niemand zusieht. Zwischen den Zeilen klebt ein winziger Apfelkern."},
    choices:[{label:"Das Versprechen leise wiederholen",text:"Du sprichst das Versprechen nur für dich. Es wird dadurch nicht kleiner, sondern schwerer zu vergessen."},{label:"Es ins Wegbuch eintragen",text:"Du schreibst die Worte auf. Vielleicht wird jemand später über denselben Satz stolpern und stehen bleiben."}]},
  {id:"mountain",title:"Die Stimmen am Berg",chapter:2,places:["farrenpoint","wendelstein"],
    intro:{farrenpoint:"Zwischen zwei Steinen liegt ein Holzspan mit eingeritzten kleinen Schuhen.",wendelstein:"Am Bergpfad führen winzige Fußspuren zwischen den Steinen hindurch."},
    story:{farrenpoint:"Von hier siehst du die Wiesen, die Filze und die Wasserläufe zugleich. Der Span trägt drei Zeichen: Apfel, Quelle, offenes Auge. Als der Wind auffrischt, klingt er für einen Moment wie eine Stimme: Wer alles oben behält, lässt unten nichts wachsen.",wendelstein:"Die Wendelstein-Männlein sind klein genug, um zwischen zwei Worten Platz zu haben. Eines fragt nach dem Wasser, eines nach dem Baum ohne Namen. Keines will wissen, wie viele Äpfel du besitzt. Sie warten darauf, ob du deine Reise als Besitz oder als Geschichte erzählst."},
    choices:[{label:"Von den Menschen im Tal erzählen",text:"Du nennst die Häuser am Jenbach und die Kinder an den Spielrinnen. Die kleinen Spuren führen ein Stück vor dir her."},{label:"Von der Wiese erzählen",text:"Du erzählst vom namenlosen Baum und den Kernen für andere. Der Wind trägt die Antwort talwärts."}]}
];
